# Generated by Django 6.0.4 on 2026-04-29 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Styling tip for this shape', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Face Shapes',
                'db_table': 'face_shapes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=20)),
                ('length_category', models.CharField(blank=True, choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hairstyles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='unisex', max_length=20)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField()),
                ('prob_heart', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('prob_oblong', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('prob_oval', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('prob_round', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('prob_square', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('primary_shape', models.ForeignKey(db_column='primary_shape_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_analyses', to='api.faceshape')),
                ('secondary_shape', models.ForeignKey(db_column='secondary_shape_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_analyses', to='api.faceshape')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analyses',
                'db_table': 'user_analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.useranalysis')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.hairstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceShapeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=1.0, help_text='Relevance weight 0-1', max_digits=3)),
                ('face_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.faceshape')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_for', to='api.hairstyle')),
            ],
            options={
                'db_table': 'face_shape_recommendations',
                'ordering': ['-score'],
                'unique_together': {('face_shape', 'hairstyle')},
            },
        ),
        migrations.CreateModel(
            name='FaceShapeAvoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('face_shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoids', to='api.faceshape')),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avoided_for', to='api.hairstyle')),
            ],
            options={
                'db_table': 'face_shape_avoid',
                'unique_together': {('face_shape', 'hairstyle')},
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.hairstyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorites',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'hairstyle')},
            },
        ),
    ]
