/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTryOnRouteImport } from './routes/api/try-on'
import { Route as ApiOgStyleRouteImport } from './routes/api/og.$style'

const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTryOnRoute = ApiTryOnRouteImport.update({
  id: '/api/try-on',
  path: '/api/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgStyleRoute = ApiOgStyleRouteImport.update({
  id: '/api/og/$style',
  path: '/api/og/$style',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/home': typeof HomeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/styles': typeof StylesRoute
  '/team': typeof TeamRoute
  '/try-on': typeof TryOnRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/api/og/$style': typeof ApiOgStyleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/home': typeof HomeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/styles': typeof StylesRoute
  '/team': typeof TeamRoute
  '/try-on': typeof TryOnRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/api/og/$style': typeof ApiOgStyleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/home': typeof HomeRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/styles': typeof StylesRoute
  '/team': typeof TeamRoute
  '/try-on': typeof TryOnRoute
  '/api/try-on': typeof ApiTryOnRoute
  '/api/og/$style': typeof ApiOgStyleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/home'
    | '/pricing'
    | '/profile'
    | '/result'
    | '/styles'
    | '/team'
    | '/try-on'
    | '/api/try-on'
    | '/api/og/$style'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/home'
    | '/pricing'
    | '/profile'
    | '/result'
    | '/styles'
    | '/team'
    | '/try-on'
    | '/api/try-on'
    | '/api/og/$style'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/analyze'
    | '/home'
    | '/pricing'
    | '/profile'
    | '/result'
    | '/styles'
    | '/team'
    | '/try-on'
    | '/api/try-on'
    | '/api/og/$style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AnalyzeRoute: typeof AnalyzeRoute
  HomeRoute: typeof HomeRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  StylesRoute: typeof StylesRoute
  TeamRoute: typeof TeamRoute
  TryOnRoute: typeof TryOnRoute
  ApiTryOnRoute: typeof ApiTryOnRoute
  ApiOgStyleRoute: typeof ApiOgStyleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/try-on': {
      id: '/api/try-on'
      path: '/api/try-on'
      fullPath: '/api/try-on'
      preLoaderRoute: typeof ApiTryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$style': {
      id: '/api/og/$style'
      path: '/api/og/$style'
      fullPath: '/api/og/$style'
      preLoaderRoute: typeof ApiOgStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AnalyzeRoute: AnalyzeRoute,
  HomeRoute: HomeRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  StylesRoute: StylesRoute,
  TeamRoute: TeamRoute,
  TryOnRoute: TryOnRoute,
  ApiTryOnRoute: ApiTryOnRoute,
  ApiOgStyleRoute: ApiOgStyleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
